### ISSUE TITLE
?edit out download tags/buttons?

### ISSUE THREAD

**Issue by dannyjnwong** [datascibc/website#1]
Tom, I saw you edited out, then reinstated the download tags. I think we should get rid of them.

**Comment by tompollard** [comment]
Hi Danny,

Sorry for the slow reply. Yep, it didn’t seem like they were worth having, but the site looked a little empty without them, so I ended up putting them back! I see you’ve taken them off now anyway, which I think is best.

I have just set up a local version of Jekyll to have a play around with the site on my laptop. Worth doing if you haven’t already done so.

Can’t remember if you are on Mac or PC…if Mac then this guide explains how: http://internet-inspired.com/wrote/install-jekyll-in-osx-mavericks/

Tom

On 28 Jan 2015, at 08:16, dannyjnwong <notifications@github.com<mailto:notifications@github.com>> wrote:

Tom, I saw you edited out, then reinstated the download tags. I think we should get rid of them.
